site_name: Parth Virani Guides
site_url: https://parthvirani-oceanmtech.github.io/parthvirani-notes/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/parthvirani-oceanmtech/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/parthvirani95?lang=en
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/parthvirani/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/parthvirani-oceanmtech"  target="_blank" rel="noopener">Parth Virani Oceanmtech Pvt Ltd</a>